### ISSUE TITLE
Can you tell me why VDSM is implemented in Python instead of Java

### ISSUE THREAD

**Issue by Master0711** [oVirt/vdsm#119]
Can you tell me why VDSM is implemented in Python instead of Java

**Comment by nirs** [comment]
@dankenigsberg do you remember the times vdsm was started?

**Comment by dankenigsberg** [comment]
Back then, Java was not even considered. What today is ovirt-engine was written in C#, and only years later was [ported to Java](http://lpeer.blogspot.com/2010/04/switching-from-c-to-java.html).

I wasn't there at the time, but given the need to write a thin wrapper to manage qemu (libvirt was out of the picture back then!) and tight integration with Linux, Python still seem like a good fit for the job. Python is a wonderful language, imho. At its best, it's pseudo-code that runs. Unfortunately, it's easy to write bad code in it, but then again - that's true for other languages too.

**Comment by Master0711** [comment]
@nirs @dankenigsberg Thank you for your answers and wish you the best！
