### ISSUE TITLE
Improve TestExecCmd in misc_test for output handling

### ISSUE THREAD

**Issue by aesteve-rh** [oVirt/vdsm#143]
### Description

In misc_tests, the executed commands in `TestExecCmd` do not consider the return code nor all the outputs to determine if the test should fail. Considering them not only will increase the test coverage, but will provide useful output for debugging.

Also, `checkSudo` function is not working as expected, resulting in runs where the test should be skipped because the user is not root, but it is instead executed and fails as a result.

### Traceback

```bash
$ tox -e storage -- -vv storage/misc_test.py::TestExecCmd::testSudo
...
self = <storage.misc_test.TestExecCmd testMethod=testSudo> 
    def testSudo(self):
        """
        Tests that when running with sudo the user really is root (or other
        desired user). 
        """ 
        cmd = [EXT_WHOAMI]
        checkSudo(cmd)
        ret, stdout, stderr = commands.execCmd(cmd, sudo=True) 
>       self.assertEqual(stdout[0].decode("ascii"), SUDO_USER) 
E       IndexError: list index out of range
storage/misc_test.py:600: IndexError
```

### Investigation

The problem seems to be related with the `-l` option of the sudo command in the `checkSudo` function: https://www.sudo.ws/docs/man/1.8.13/sudo.man/

```
If a command is specified and is permitted by the security policy, the fully-qualified path to the 
command is displayed along with any command line arguments. If command is specified but 
not allowed, sudo will exit with a status value of 1.
```

So doing:

```bash
$ rpm -q sudo   
sudo-1.9.7p2-2.fc35.x86_64

$ sudo -l -n whoami
/usr/bin/whoami
```

Just prints the full path, no error, and `checkSudo` fails to recognize the need for sudo, which ends up causing the execution of the command to fail.

### Proposed Solution

- For the additional checks of the return code, when rc is `!=0` the test should fail and print the error output for a more descriptive log.
- For the `checkSudo`, replace the function with the `@requires_root` decorator. Eventually might be good idea to remove `checkSudo` code completely.

**Comment by nirs** [comment]
@aesteve-rh See comments on #144, they apply to this issue as well.
