### ISSUE TITLE
Improve test_write_file_direct_true_aligned 

### ISSUE THREAD

**Issue by aesteve-rh** [oVirt/vdsm#144]
### Description

`outofprocess_test` uses temporary files created by pytest fixture. However, when using these files, `test_write_file_direct_true_aligned` will not raise with file systems without minimum block size for direct I/O (e.g., btrfs).

### Traceback

```bash
$ tox -e storage -- -vv storage/outofprocess_test.py::test_write_file_direct_true_unaligned
...
oop_cleanup = None, tmpdir = local('/var/tmp/vdsm/test_write_file_direct_true_un0')   
    def test_write_file_direct_true_unaligned(oop_cleanup, tmpdir): 
        iop = oop.getProcessPool("test")
        path = str(tmpdir.join("file"))
>       with pytest.raises(OSError) as e:
E       Failed: DID NOT RAISE <class 'OSError'> 

storage/outofprocess_test.py:1010: Failed  
```
while:
```bash
$ df -hT /var/tmp
Filesystem                                            Type   Size  Used Avail Use% Mounted on
/dev/mapper/luks-08653fbb-0d5f-4a76-be60-30be4377cf5d btrfs  476G  119G  357G  25% /
```
### Proposed solution

To avoid such issues, the tests should use user storage instead of random storage from the host running the tests.

**Comment by nirs** [comment]
@aesteve-rh can you change this issue to describe the problem?

- Describe the issue
- Include the traceback from the test
- Provide additional data if you have, explaining the issue or hinting on the solution

The issue should have enough data so someone else can pick it up easily.
