### ISSUE TITLE
vdsm - libvirt integration in el9

### ISSUE THREAD

**Issue by ahadas** [oVirt/vdsm#201]
vdsm doesn't work on el9stream due to several changes
- libvirt has been split into several independent daemons and likely need furter configuration (virtqemud, virtsecretd, maybe others?)
- vdsm configures sasl with mech_list: scram-sha-1. That is no longer supported and should use scram-sha-256
- same problem exists for VNC in /etc/sasl2/qemu.conf

Original bug: https://bugzilla.redhat.com/2032980

**Comment by michalskrivanek** [comment]
when you're opening it here then please reflect bugzilla updates - vdsm does work. scram-sha-256 has been changed AFAICT...so I'm not sure what's even missing and why the bug is/was still open.

**Comment by ahadas** [comment]
thanks for updating this one @michalskrivanek
