### ISSUE TITLE
Fix connect_all error log 

### ISSUE THREAD

**Issue by bennyz** [oVirt/vdsm#252]
https://github.com/oVirt/vdsm/blob/d43d31f5a1f165bcff68ac9b4d38645c2761015f/lib/vdsm/storage/storageServer.py#L597-L598

Message is missing "not", and  should be: `"Could not configure connection to %s and iface %s"`, or maybe switch to f-strings

**Comment by aesteve-rh** [comment]
Logging package is [optimized](https://docs.python.org/3/howto/logging.html#optimization) for % formatting, the advantage being that formatting the parameters is deferred until the log is actually going to be printed, and only if it is. 

Otherwise the proposed fix looks fine.
