### ISSUE TITLE
Remove vdsm.virt.secret module

### ISSUE THREAD

**Issue by nirs** [oVirt/vdsm#30]
Libvirt secrets are not used now since we disabled old Cinder support, so the code can be removed now
to avoid the (likely false positive) code scanning reports[1].

The secret APIs were part of tech-preview feature, so we should be able to remove them
without notice.

[1] https://github.com/oVirt/vdsm/security/code-scanning/168

**Comment by nirs** [comment]
@bennyz @ahadas what do you think?

**Comment by ahadas** [comment]
when did we remove the old Cinder support? recently or long time ago?

**Comment by nirs** [comment]
@sleviim can you update on legacy Cinder removal?

**Comment by sleviim** [comment]
@nirs not sure I get you :)
Old cinder integration was removed on webadmin, restapi, and api-model:
https://gerrit.ovirt.org/q/topic:remove-old-cinder

**Comment by bennyz** [comment]
> @bennyz @ahadas what do you think?

I recall we discussed this and said that we should keep it as it can be useful for implementing support for librbd in MBS, right?

**Comment by nirs** [comment]
OK, lets close this, since this module may be useful in the future.
